esphome:
  name: esp-rego1000
  includes:
    - regovardump.h

esp32:
  board: esp32-evb
  framework:
    type: arduino

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  manual_ip:
    static_ip: 192.168.0.21
    gateway: 192.168.0.1
    subnet: 255.255.255.0

# Enable logging
logger:
  level: INFO
  baud_rate: 0 # disable logging over uart
  
# Enable Home Assistant API
api:
  encryption:
    key: !secret ha_api_encryption_key

ota:
  password: !secret ota_password


custom_component:
  - id: rego_sensor
    lambda: |-
      RegoReader* rego_sensor = rego_sensor->getInstance();
      return {rego_sensor};
