esphome:
  name: esp-rego1000
  includes:
    - regovardump.h

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp-rego1000"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:
  level: INFO
  baud_rate: 0 # disable logging over uart
  
# Enable Home Assistant API
api:
  password: !secret hass_api_password

ota:
  password: !secret ota_password

canbus:
  - platform: esp32_can
    id: can0
    can_id: 0
    tx_pin: GPIO23
    rx_pin: GPIO22
    bit_rate: 125kbps

custom_component:
  - id: rego_sensor
    lambda: |-
      RegoReader* rego_sensor = rego_sensor->getInstance(id(can0));
      return {rego_sensor};
