name: ESPHome

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: esphome/esphome:stable

    steps:
    - uses: actions/checkout@v2
    - name: ESPHome
      run: |
        echo "{wifi_ssid: \"TEST_SSID\",wifi_password: \"TEST_PASS\",fallback_password: \"\",hass_api_password: \"\",ota_password: \"\"}" > secrets.yaml
        esphome -s rego_version rego1000-v1.12.1-variables.yaml compile rego1000.yaml
