name: ESPHome

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: ESPHome
      run: |
        python -m pip install --upgrade pip
        pip install esphome
        echo "{wifi_ssid: \"TEST_SSID\",wifi_password: \"TEST_PASS\",fallback_password: \"\",hass_api_password: \"\",ota_password: \"\"}" > secrets.yaml
        esphome -s rego_version 1.12.1 compile rego1000.yaml
